<?php

$t_language_text_section_content_array = [
    'description' => 'Mit diesem Module können sie Makaira nutzen',
    'title'       => 'Makaira Gambio Connect',
    'settings'           => 'Einstellungen',
    'makaira_url'        => 'Makaira URL',
    'makaira_instance'   => 'Makaira Instanz',
    'makaira_secret'     => 'Makaira Secret',
    'makaira_active_search' => 'Makaira aktive suche',
    'stripe_checkout_session' => 'Stripe Checkout Session ID',
    'stripe_override'        => 'Nur nutzen, wenn ein eigener Vertrag mit Makaira besteht',
    'welcome' => 'Willkommen',
    'faq' => 'FAQ',
    'document' => 'Dokument',
    'my_account' => 'Konto',
    "save" => "Speichern",
    "manual_setup" => "Manuelle Einrichtung",
    'manual_setup_description' => 'Nur anwenden, wenn Sie bereits Makaira-Kunde sind und über die folgenden Werte verfügen.',
    'saved' => 'Einstellungen gespeichert',
    'success' => 'Erfolg',
    'warning' => 'Warnung',
    'invalid' => 'Einige Einstellungen wurden nicht gespeichert. Ungültige Eingabe.',
    'account' => 'Konto',
    'in_setup_description' => 'Makaira wird eingerichtet. Dieser Vorgang kann einige Minuten dauern. Vielen Dank für Ihre Geduld.',
];
