<?php

$t_language_text_section_content_array = [
    'description' => 'Mit diesem Module können sie Makaira nutzen',
    'title'       => 'Makaira Gambio Connect',
    'settings'           => 'Einstellungen',
    'makaira_url'        => 'Makaira URL',
    'makaira_instance'   => 'Makaira Instanz',
    'makaira_secret'     => 'Makaira Secret',
    'makaira_active_search' => 'Makaira aktive suche',
    'welcome' => 'Willkommen',
    'faq' => 'FAQ',
    'document' => 'Dokument',
    'my_account' => 'Konto',
    "save" => "Speichern",
    "manual_setup" => "Manuelle Einrichtung",
    'manual_setup_description' => 'Nur anwenden, wenn Sie bereits Makaira-Kunde sind und über die folgenden Werte verfügen.',
    'saved' => 'Einstellungen gespeichert',
    'success' => 'Erfolg',
    'warning' => 'Warnung',
    'invalid' => 'Einige Einstellungen wurden nicht gespeichert. Ungültige Eingabe.',
    'account' => 'Konto',
    'in_setup_description' => 'Makaira wird eingerichtet. Dieser Vorgang kann einige Minuten dauern. Vielen Dank für Ihre Geduld.',
    'goto_makaira' => 'Zu Makaira',
    'reco_title' => 'Recommendations',
    'reco_cross_selling_description' => 'Hier können sie einstellen welche makaira Recommendations sie nutzen möchten, die id finden sie im makaira dashboard',
    'goto_makaira_recos' => 'Zu Makaira Recommendations',
    'reco_cross_selling' => 'Cross Selling Recommendations ID',
    'reco_reverse_cross_selling' => 'Reverse Cross Selling Recommendations ID',
    'cron_status' => 'Cronjob-Status',
    'queue_length' => 'Produkte Warteschlangenlänge',
    'last_sync' => 'Letzte Synchronisation',
    'cron_status_1' => 'aktiv',
    'cron_status_0' => 'inaktiv',
    'account_title' => 'Konto',
];
