name: Stage Deployment Workflow
on:
  push:
    branches:
      - main
      - stage
jobs:
  stage-deployment:
    name: Trigger a new stage deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Create new Gitlab pipeline for Gambio
        run: |
          curl -XPOST -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "https://gitlab.marmalade.de/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/pipeline?ref=${{ secrets.GITLAB_GAMBIO_REF }}"
