name: Deploy Stage
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
        with:
          host: ${{ secrets.GITLAB_URL }}
          trigger_token: ${{ secrets.GITLAB_DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.GITLAB_DEPLOY_ACCESS_TOKEN }}
          id: ${{ vars.GITLAB_PROJECT_ID }}
          ref: ${{ vars.GITLAB_REF }}
