<?php

$t_language_text_section_content_array = [
    'description' => 'You can use Makaira with this module',
    'title' => 'Makaira Gambio Connect',
    'settings' => 'Settings',
    'makaira_url' => 'Makaira URL',
    'makaira_instance' => 'Makaira instance',
    'makaira_secret' => 'Makaira secret',
    'makaira_active_search' => 'Makaira active search',
    'welcome' => 'Welcome',
    'faq' => 'FAQ',
    'document' => 'Document',
    'my_account' => 'My account',
    'save' => 'Save',
    'manual_setup' => 'Manual Setup',
    'manual_setup_description' => 'Only apply if you are already a Makaira customer and have the following values.',
    'saved' => 'Settings saved',
    'success' => 'Success',
    'warning' => 'Warning',
    'invalid' => 'Some settings were not saved. Invalid input.',
    'account' => 'Account',
    'in_setup_description' => 'Makaira is being set up. This process may take a few minutes. Thank you for your patience.',
    'goto_makaira' => 'To Makaira',
    'reco_title' => 'Makaira Recommendations',
    'reco_cross_selling_description' => 'Here you can configure which Makaira Recommendations you want to use. Find the ID in your Makaira dashboard.',
    'goto_makaira_recos' => 'Go to Makaira Recommendations',
    'reco_cross_selling' => 'Cross Selling Recommendations ID',
    'reco_reverse_cross_selling' => 'Reverse Cross Selling Recommendations ID',
    'cron_status' => 'Cronjob Status',
    'cron_status_1' => 'active',
    'cron_status_0' => 'inactive',
    'queue_length' => 'Queue Length',
    'last_sync' => 'Last Sync',
    'account_title' => 'Account',

];
